added StakeHolder-Upload-Multi-Part-Document
hyperwallet/php-sdk pull request #48
Opened 2020-10-13 10:45 UTC by madhankumar3103

i have added stakeholder upload multi part documents

2020-10-13 16:14 UTC, Rrathinasabapath requested changes
Please make the changes.

2020-10-13 17:37 UTC, arao6 commented on src/Hyperwallet/Hyperwallet.php
> +     * Upload documents for user endpoint
Please change the name of the model to BusinessStakeholder

2020-10-13 18:09 UTC, arao6 commented on src/Hyperwallet/Hyperwallet.php
> +     *
Pls update Businessusers to BusinessStakeholders

2020-10-14 05:22 UTC, Rrathinasabapath requested changes
Pls fix the one comment.

2020-10-14 07:00 UTC, ramahalingam commented on src/Hyperwallet/Hyperwallet.php
> +        $body = $this->client->putMultipartData('/rest/v4/users/{user-token}/business-stakeholders/{business-stakeholders}', array('user-token' => $userToken,'business-stakeholders' => $businessToken
{business-stakeholders} can be renamed.

2020-10-14 07:27 UTC, arao6 approved these changes

2020-10-14 09:05 UTC, Rrathinasabapath approved these changes
Reviewed the changes. Ready to be reviewed by Peter.

2020-10-14 18:10 UTC, vkorotchenko approved these changes

2020-10-15 05:10 UTC, ramahalingam approved these changes

2020-10-15 16:56 UTC, merged