Feature/v4 user endpoint php update list multipart statustransition
hyperwallet/php-sdk pull request #54
Opened 2020-10-18 18:05 UTC by Rrathinasabapath

Added changes for User enpoint for:
*Update
*List
*Multipart upload
*User status transition

2020-10-19 04:23 UTC, ramahalingam commented on tests/Hyperwallet/Tests/HyperwalletTest.php
> +    private $includeIntegrationTest = false; //change this value to true if integration tests have to be run
Pls remove this unused variable.

2020-10-19 04:39 UTC, Rrathinasabapath commented on tests/Hyperwallet/Tests/HyperwalletTest.php
> +    private $includeIntegrationTest = false; //change this value to true if integration tests have to be run
Removed the unused line

2020-10-19 06:12 UTC, ramahalingam requested changes
Resolve the test failures.

2020-10-19 08:21 UTC, arao6 reviewed
Build seems to be failing. Please fix the failures mentioned

2020-10-20 19:02 UTC, arao6 approved these changes

2020-10-20 22:57 UTC, peter-joseph approved these changes

2020-10-20 23:40 UTC, merged