Removed 'links' attribute for V4 Balances
hyperwallet/php-sdk pull request #56
Opened 2020-10-20 17:01 UTC by skambar110

Removed 'links' attribute for V4 Balances.

2020-10-20 21:42 UTC, arao6 requested changes
Please rectify the errors that are causing the build to fail.
Undefined property: Hyperwallet\Response\ListResponse::$links  
Above error in the ListBalances test methods - 6 errors.

2020-10-21 18:27 UTC, arao6 approved these changes

2020-10-21 19:32 UTC, Rrathinasabapath approved these changes
Reviewed the changes. Ready to be reviewed by Peter before merging.

2020-10-21 19:41 UTC, peter-joseph approved these changes

2020-10-21 20:08 UTC, merged